eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
server:
  port: 8080
spring:
  cloud :
    gateway :
      discovery:
        locator:
          enabled : true
          lowerCaseServiceId : true

  application:
    name: api-gateway



